version: "3.9"
# services:
#   db:
#     image: postgres:15
#     restart: unless-stopped
#     environment:
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#   adminer:
#     image: adminer
#     restart: unless-stopped
#     ports:
#       - "8080:8080"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: reginsight_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: reginsight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
volumes:
  postgres_data: